site_name: hut-services
repo_url: https://github.com/wodore/hut-services
site_url: https://wodore.github.io/hut-services
site_description: Services to retrieve information about (mountain) huts.
site_author: TBxy
edit_uri:
  edit/main/docs/
  #repo_name: wodore/hut-services
repo_name: hut-services
copyright: Maintained by <a href="tb@wodore.com">TBxy</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          load_external_modules: true
          #setup_commands:
          #  - import sys
          #  - sys.path.append('../src')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wodore/hut-services
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hut-services

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
